version: '3.2'

services:
  
  demofinal-db:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=MEETUP_Amst3rd@m
    volumes:
      - rupesh-volume:C:/var/lib/db
    networks:
      - app-net

  web:
    image: dockerdemo
    ports:
      - "97:80"
    env_file:
      - a.env
    environment:
      - ProductContext=Server=demofinal-db;Initial Catalog=Product;User ID= sa; Password=MEETUP_Amst3rd@m
    networks:
      - app-net
networks:
  app-net:
    external:
      name: nat
      
volumes:
  rupesh-volume: