version: '3.2'

services:
  
  demodocker-db:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=MEETUP_Amst3rd@m
    volumes:
      # Specify an absolute path mapping
      - C:\Temp:C:\Temp
    networks:
      - app-net

  web:
    image: demodocker
    ports:
      - "98:80"
    tty: true
    environment:
      - DB_CONNECTION_STRING=Server=demodocker-db;Database=ProductLaunch;User Id=sa;Password=MEETUP_Amst3rd@m;
    networks:
      - app-net
networks:
  app-net:
    external:
      name: nat